### ISSUE TITLE
v1.0.5 is broken, new release is needed after merge of #6

### ISSUE THREAD

**Issue by probil** [vinayakkulkarni/v-offline#7]
The current version of `v-offline` is broken on the `npm`.
```
Cannot find module "dist/v-offline.min.js" in package v-offline@1.0.5
```
So, it can't be used. 
It's partially my fault (because of #5) I didn't check that right in the branch before creating PR. Sorry.
Please, rollback `1.0.5` and republish (after PR #6 was merged) or create a new release `1.0.6`

If everything is fine, this link should return minified javascript file:
https://unpkg.com/v-offline (clickable)

@vinayakkulkarni

**Comment by vinayakkulkarni** [comment]
- [x] Done, I forgot to push.. lol.. I'm really sorry bout the delays man.. been really hectic few days at work..

**Comment by probil** [comment]
I see it fixed in `1.0.6`. Thank you. 👍
